export const data = [
  {
    id: 1,
    name: 'Broiler Chicken',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644871559/food-denx/products/chicken_lilagk.png',
    tag: '1Kg, Pricetag',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 0,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 2,
    name: 'Beef Bone',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644871618/food-denx/products/beef_bone_udpbnu.png',
    tag: '1Kg, Pricetag',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 3,
    name: 'Organic Banana',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644871559/food-denx/products/Banana_qnglaq.png',
    tag: '1Kg, Pricetag',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 4,
    name: 'Egg Chicken Red',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644871559/food-denx/products/Egg_l3wcvx.png',
    tag: '4pcs, Price',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 5,
    name: 'Sprite Can',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644871559/food-denx/products/sprite_uovoud.png',
    tag: '325ml, Price',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 6,
    name: 'Bell Pepper Red',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644871559/food-denx/products/Bell_Pepper_zawwdp.png',
    tag: '1Kg, Pricetag',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
];

export const bestofferdata = [
  {
    id: 1,
    name: 'Organic Italian parsley',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644883170/food-denx/products/parsley_kem5ug.png',
    tag: '1Kg, Pricetag',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 0,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 2,
    name: 'Beef Bone',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644871618/food-denx/products/beef_bone_udpbnu.png',
    tag: '1Kg, Pricetag',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 3,
    name: 'Organic Banana',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644871559/food-denx/products/Banana_qnglaq.png',
    tag: '1Kg, Pricetag',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 4,
    name: 'Organic Grape Tomatoe',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644883170/food-denx/products/tomatoe_jbypzw.png',
    tag: '4pcs, Price',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 5,
    name: 'Organic Brocoli',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644883170/food-denx/products/brocoli_sd1fie.png',
    tag: '325ml, Price',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 6,
    name: 'Straw Berry',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644883170/food-denx/products/stawberry_d2vrv8.png',
    tag: '1Kg, Pricetag',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
];

export const allproducts = [
  {
    id: 1,
    name: 'Broiler Chicken',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644871559/food-denx/products/chicken_lilagk.png',
    tag: '1Kg, Pricetag',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 0,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 2,
    name: 'Beef Bone',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644871618/food-denx/products/beef_bone_udpbnu.png',
    tag: '1Kg, Pricetag',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 3,
    name: 'Organic Banana',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644871559/food-denx/products/Banana_qnglaq.png',
    tag: '1Kg, Pricetag',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 4,
    name: 'Egg Chicken Red',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644871559/food-denx/products/Egg_l3wcvx.png',
    tag: '4pcs, Price',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 5,
    name: 'Sprite Can',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644871559/food-denx/products/sprite_uovoud.png',
    tag: '325ml, Price',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 6,
    name: 'Bell Pepper Red',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644871559/food-denx/products/Bell_Pepper_zawwdp.png',
    tag: '1Kg, Pricetag',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 1,
    name: 'Organic Italian parsley',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644883170/food-denx/products/parsley_kem5ug.png',
    tag: '1Kg, Pricetag',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 0,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 2,
    name: 'Beef Bone',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644871618/food-denx/products/beef_bone_udpbnu.png',
    tag: '1Kg, Pricetag',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 3,
    name: 'Organic Banana',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644871559/food-denx/products/Banana_qnglaq.png',
    tag: '1Kg, Pricetag',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 4,
    name: 'Organic Grape Tomatoe',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644883170/food-denx/products/tomatoe_jbypzw.png',
    tag: '4pcs, Price',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 5,
    name: 'Organic Brocoli',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644883170/food-denx/products/brocoli_sd1fie.png',
    tag: '325ml, Price',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
  {
    id: 6,
    name: 'Straw Berry',
    image:
      'https://res.cloudinary.com/dyvisacbu/image/upload/v1644883170/food-denx/products/stawberry_d2vrv8.png',
    tag: '1Kg, Pricetag',
    price: '499',
    desc: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
    stock: 300,
    SKU: 'sdhfgidj3djiuJHIUDSFFF',
    Brand: 'NO Brand',
  },
];
